### PR TITLE
Performance improvement

### PR DESCRIPTION
**Pull request by davidebianchi**
Hi, I'm issued slow performance converting very big swagger to openapi using `convertObj` function.

After reading the code, I found some function that could be changed to significantly increase the performance. 
I wrote benchmark of the converted function before and after the changes.

Before:
```
jpescape x 1,095,631 ops/sec ±0.30% (85 runs sampled)
jpunescape x 1,074,826 ops/sec ±0.30% (90 runs sampled)
circular clone x 814,184 ops/sec ±1.22% (90 runs sampled)
swagger2openapi convertObj with text x 216 ops/sec ±1.88% (80 runs sampled)
swagger2openapi convertObj without text x 950 ops/sec ±2.20% (86 runs sampled)
```

After
```
jpescape x 1,741,216 ops/sec ±0.70% (89 runs sampled)
jpunescape x 1,524,805 ops/sec ±0.44% (88 runs sampled)
circular clone x 1,059,002 ops/sec ±0.32% (90 runs sampled)
swagger2openapi convertObj with text x 609 ops/sec ±1.85% (84 runs sampled)
swagger2openapi convertObj without text x 1,466 ops/sec ±2.30% (84 runs sampled)
```

I found that a bottleneck converting swagger to openapi is due to the conversion to yaml string (I add a benchmark also with text included or not, and change the used library with one more performant).
Could be an idea to add  an options to skip this block if is not required? 
For the benchmark I set text options to `true`.

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Thanks for the PR.

I would be interested in seeing some hard numbers, e.g. how big your input OpenAPI 2.0 document is and what the elapsed time is in ms or s to convert it.

Granted performance has not been a consideration so far in `oas-kit`, but it has not seemed to be an issue up to now. Conversions are generally one-off actions, not something run in a loop as in a benchmark. I've run conversions over the whole of the [APIs.guru openapi-directory](https://github.com/APIs-guru/openapi-directory) and not seen any excessively lengthy conversions.

* The `jpescape` / `jpunescape` change looks like a good change
* We have recently moved **from** `js-yaml` because it is not always YAML spec compliant and is significantly larger when webpacked than `yaml`. We are not interested in moving back at this time
* We are not looking to take on dependencies from `lodash` at this time as it might encourage further creep into the codebase

> I found that a bottleneck converting swagger to openapi is due to the conversion to yaml string (I add a benchmark also with text included or not, and change the used library with one more performant).
Could be an idea to add an options to skip this block if is not required?
For the benchmark I set text options to true.

As you found, you can set `options.text` to a truthy value to prevent stringification. I think all that's needed here is some additional documentation.

**Comment by davidebianchi** [comment]
As of now my input document is a file of about 10Mb and the conversion takes about 40 seconds. I can't post the swagger because it is not public.

* perfect
* For the conversion to string why is it inside the library? If a user must convert to string, couldn't it be done outside before calling the function? For the `js-yaml` library it's not a problem, once skipped the conversion.
* It is not a dependency from lodash, but only from `lodash.cloneDeep`. I think it is worse to depend from a copy/pasted code from stackoverflow (in the same page, it is suggested to use a well known and well tested library instead of the code)

**Comment by MikeRalphson** [comment]
> For the conversion to string why is it inside the library? If a user must convert to string, couldn't it be done outside before calling the function? For the js-yaml library it's not a problem, once skipped the conversion.

It is present for two reasons - to ensure the `options` object always has a `text` property regardless of whether `convertObj`, `convertStr`, `convertStream` etc were called; this is used by the validator / linter to enable testing of metadata such as the number of lines in the input file against a linter rule.

> It is not a dependency from lodash, but only from lodash.cloneDeep. I think it is worse to depend from a copy/pasted code from stackoverflow (in the same page, it is suggested to use a well known and well tested library instead of the code)

`lodash.*` modules are just the component parts of `lodash` and I don't want to encourage the use of `lodash` or its component parts in this project. Lodash is generally not required with ES6+ and it does not recently have much of a good security record.

Can you explain why the clone test was changed? Generally for regression spotting, it's not a good idea to make changes to both the tests and the implementation in one PR.

**Comment by davidebianchi** [comment]
I changed the test before the implementation. The reason is that the circular deep clone was tested upon a non circular object, so the previous test passes also using the deepClone function. 

I added back the previous test to keep track of evenutal regression

**Comment by MikeRalphson** [comment]
I've found one cause of slow performance in `yaml.stringify` - hopefully this will get merged https://github.com/eemeli/yaml/pull/137 and I will cut a new release.

**Comment by MikeRalphson** [comment]
Many thanks for starting the conversation on this. I've taken the `jpescape` / `jpunescape` change, and limited the amount of yaml stringification used, and upgraded to `yaml` 1.8.0.

**Pull request closed without merging**
