### PR TITLE
Create index.d.ts for swagger2openapi

### PR DESCRIPTION
**Pull request by hosseinmd**
Just for ignore typescript error

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Hmm. When you say "Just for ignore typescript error" - where does this error occur (in what tool, context etc). 

It doesn't look as if just setting anything to type `any` is really helpful?

**Comment by hosseinmd** [comment]
On typescript project modules have to be a typescript or at least has a .d.ts.

> It doesn't look as if just setting anything to type any is really helpful?

Yes I can ignore typescript error.

However that is so better to define whole types of exported functionality. But I don't have enough knowledge about this module

**Comment by hosseinmd** [comment]
I add whole functions types.

**Comment by hosseinmd** [comment]
Please review

**Comment by MikeRalphson** [comment]
This seems to be solvable in your typescript project, see https://medium.com/@steveruiz/using-a-javascript-library-without-type-declarations-in-a-typescript-project-3643490015f3

**Comment by hosseinmd** [comment]
> This seems to be solvable in your typescript project, see https://medium.com/@steveruiz/using-a-javascript-library-without-type-declarations-in-a-typescript-project-3643490015f3

I solved it in my own project. But this PR is useful for other users.

**Comment by MikeRalphson** [comment]
Unless we can declare correct types for the exported API of all of the packages in this repository, I think it is better not to include this PR in its current state.

**Pull request closed without merging**
