### PR TITLE
swagger2openapi: enhancements to form/body parameter conversions

### LINKED ISSUE #112: Extensions on body and form parameters are not retained
When I use swagger2openapi (command line), extensions defined on body and form parameters within a swagger 2.0 apispec are not copied to the resulting openapi 3 apispec.
Note: I am currently using swagger2openapi v3.2.13

### Checklist

- [X] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [X] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong

### Detailed Description
I have a swagger 2.0 apispec which contains extensions in various places.   The extensions set on body and form parameters seem to be lost in the conversion process.   I would have expected that extensions set on a body param would be carried forward and set on the resulting requestBody object.   For extensions set on form params, I would expect those to be carried forward and set on the schema property which corresponds to the form param.

Here is a small swagger 2.0 apispec which can serve as a testcase:

```
{
    "swagger":"2.0",
    "info":{
        "title":"Testcase for swagger2openapi issue",
        "description":"This is a testcase which demonstrates a problem in swagger2openapi.  Specifically, extension properties defined on body and form parameters are not carried forward to the requestBody object within the converted apispec.",
        "version":"1.0.0",
        "x-info-extension":"Example of an extension defined for the 'info' object."
    },
    "x-root-extension": "Example of an extension set at the root level.",
    "paths":{
        "/testcase/v1/person":{
            "post":{
                "summary":"Body param test #1",
                "description":"Testcase that uses a body param which has extensions set on it.",
                "operationId":"createPerson",
                "consumes":[
                    "application/json"
                ],
                "parameters":[
                    {
                        "name":"person",
                        "in":"body",
                        "required":true,
                        "description":"The person to be created.",
                        "schema":{
                            "$ref":"#/definitions/Person"
                        },
                        "x-body-extension":"This is an example of an extension defined on a body parameter."
                    }
                ],
                "responses":{
                    "201":{
                        "description":"Created"
                    },
                    "default":{
                        "description":"An error occurred."
                    }
                },
		"x-operation-extension": "Example of an extension set on the 'createPerson' operation."
            }
        },
        "/testcase/v1/forms":{
            "post":{
                "summary":"Form param test #1",
                "description":"Testcase that uses form params which have extensions set on them.",
                "operationId":"createForms",
                "consumes":[
                    "multipart/form-data"
                ],
                "parameters":[
                    {
                        "name":"stringPart",
                        "in":"formData",
                        "required":true,
                        "description":"A form part which is a string.",
                        "type":"string",
                        "x-alternate-name":"alternateStringPart"
                    },
                    {
                        "name":"filePart",
                        "in":"formData",
                        "required":true,
                        "description":"A form part which is a file.",
                        "type":"file",
                        "x-file-content-types":[
                            "application/octet-stream",
                            "application/zip"
                        ],
                        "x-include-filename":true,
                        "x-alternate-name":"alternateFilePart"
                    }
                ],
                "responses":{
                    "201":{
                        "description":"Created"
                    },
                    "default":{
                        "description":"An error occurred."
                    }
                },
		"x-operation-extension": "Example of an extension set on the 'createForms' operation."
            }
        }
    },
    "definitions":{
        "Person":{
            "type":"object",
            "description":"Models a person.",
            "properties":{
                "name":{
                    "type":"string",
                    "description":"Person's name."
                },
                "age":{
                    "type":"integer",
                    "description":"Person's age."
                }
            },
	    "required": ["name", "age"]
        }
    }
}
```

### PR DESCRIPTION
**Pull request by padamstx**
Fixes #112 #113

Why:
When converting swagger 2.0 apispecs to openapi 3,
swagger2openapi is not currently copying extensions found
on form and body parameters.  Extensions found on form parameters
should (IMO) be copied to the resulting schema property in the
converted openapi3 apispec.
Likewise, extensions found on body parameters should (IMO) be copied
to the resulting requestBody within the converted apispec.
Along with this issue re: extensions, it would be nice if swagger2openapi
could optionally set an extension to preserve the body parameter name
from the input swagger 2.0 apispec.
While working on the above two issues, I also discovered a very subtle
bug where a referenced form parameter of type "file" is not properly
converted to a schema property with type=file/format=binary.

What:
This PR adds support for copying extensions from form and body parameters
to the appropriate location in the converted apispec.   Also, it
adds support for a new "--rbname" command line option which the user can
specify to indicate the name of the extension to use within the converted
apispec to preserve the body parameter name from the input apispec.
This extension will be set on the operation within the converted apispec.
I suspect a common use of this will be that folks who are using code
generators based on openapi-generator will use:
    --rbname x-codegen-request-body-name

### CODE REVIEW

**Comment by padamstx** [comment]
@MikeRalphson, javascript is not one of my strengths, so I wouldn't be surprised to learn that there are better ways to do what I did.   Also, I wasn't sure if I should check in the package-lock.json file or not, so I included it in the commit, but if that was wrong just let me know and I can amend the commit and re-submit.

**Comment by padamstx** [comment]
Also, here is a testcase I used to implement the changes in case you wan to give it a try:
[rbtest.zip](https://github.com/Mermade/oas-kit/files/2658590/rbtest.zip)

**Comment by padamstx** [comment]
I removed my "fix" (such as it was) for issue #117 (it caused 2 test failures) and pushed an amended commit.

**Comment by padamstx** [comment]
@MikeRalphson, after initially submitting my PR, I realized that I really should add a new testcase for my changes.   So, after adding a new test/s2o-test/issue112 directory containing swagger.yaml and openapi.yaml files like the other tests, I can now see 37 tests running and passing (it was 35 prior), so all good.   But then, I wanted to explicitly cause it to fail to make sure I understand how the test framework works :)   So I modified the openapi.yaml file so that the actual results from the conversion would not compare cleanly but for the life of me I can't get it to fail.   I can manually run the converter and then diff with openapi.yaml and I can see differences, but something is odd in the way that oas-validate.js is running the tests and comparing results.    Anyway, is there some magic going on here that I might be missing?   :)
I'll commit my new testcase so you can take a look if you like.   Thanks!

**Comment by padamstx** [comment]
I've added a testcase (which now actually passes :) ).   I'm fairly new to javascript and mocha so it took me a bit to figure things out, but I think I have a valid testcase now :)
Due to issue #117, the s2o output for this testcase is not 100% correct, but it is "correct" when taking into account that issue.

**Comment by MikeRalphson** [comment]
Looks good to me. Will pull and test.

**Pull request merged**
