### PR TITLE
[Feature] Pick name of the body 

### PR DESCRIPTION
**Pull request by js2me**

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Are you trying to set a `name` property on `requestBody` objects? In OAS v3.0 there is no such property.

**Comment by js2me** [comment]
@MikeRalphson no I want to get body name from Swagger 2.0.
Just I have a schema part where I see field `"name"`
image

**Comment by MikeRalphson** [comment]
As I said, in OAS 3.0 you cannot have a `name` property on a `requestBody` object, the resultant OAS 3.0 document would not validate.

**Comment by js2me** [comment]
@MikeRalphson Ok, sorry

**Comment by MikeRalphson** [comment]
I suggest you look at the following option:

--rbname Extension to use to preserve body parameter names in converted operations

**Comment by js2me** [comment]
@MikeRalphson yep! That's what I'm looking for.
Next time, will see documentation in more detail :)

**Comment by MikeRalphson** [comment]
No problem, glad we got it sorted.

**Pull request closed without merging**
